import uuid
from pptx import Presentation
from pptx.util import Inches
from app.models import PresentationRequest
from app.presentation_store import store

def generate_presentation(payload: PresentationRequest):
    prs = Presentation()
    
    # Add Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = payload.topic
    slide.placeholders[1].text = "Generated by Slide Generator API"

    # Add a few content slides
    for i in range(payload.config.num_slides - 1):
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = f"Slide {i+1}"
        body_shape = slide.shapes.placeholders[1]
        tf = body_shape.text_frame
        tf.text = f"Point 1 about {payload.topic}"
        for j in range(2, 5):
            tf.add_paragraph().text = f"Point {j}"

    file_id = str(uuid.uuid4())
    file_path = f"samples/{file_id}.pptx"
    prs.save(file_path)

    store[file_id] = {"file_path": file_path, "topic": payload.topic, "config": payload.config.dict()}
    return file_id, file_path
